const receptionIntro=command.querySelector('.intro');receptionIntro.querySelector('h1').innerHTML='Ухаалаг ирээдүйд<br><span>тавтай морил.</span>';receptionIntro.querySelector('p').textContent='Таны өдөр тутмын ажлыг хөнгөвчлөх AI туслахууд. Oyun Technology-той шинэ боломжийг нээгээрэй.';
const receptionNav=document.createElement('nav');receptionNav.className='reception-nav';receptionNav.setAttribute('aria-label','Үндсэн цэс');receptionNav.innerHTML='<button data-reception="solutions">AI шийдлүүд</button><button data-reception="oyun">Оюун</button><button data-reception="about">Бидний тухай</button><button data-reception="contact">Холбоо барих</button>';command.querySelector('.topbar').append(receptionNav);
const receptionActions=document.createElement('div');receptionActions.className='reception-actions';receptionActions.innerHTML='<button class="reception-primary" data-reception="solutions">Боломжуудыг нээх ↗</button><button class="reception-secondary" data-reception="oyun"><span class="play-circle">✦</span>Оюунтай танилцах</button>';receptionIntro.append(receptionActions);
const receptionPanel=command.querySelector('.control-panel');receptionPanel.setAttribute('aria-label','Дэлгэрэнгүй мэдээлэл');receptionPanel.setAttribute('inert','');const panelTopRight=document.createElement('div');panelTopRight.className='panel-top-right';panelTopRight.append(receptionPanel.querySelector('.panel-top .live'));const panelClose=document.createElement('button');panelClose.className='panel-close';panelClose.setAttribute('aria-label','Мэдээлэл хаах');panelClose.textContent='×';panelTopRight.append(panelClose);receptionPanel.querySelector('.panel-top').append(panelTopRight);let receptionTrigger;
function closeReception(){receptionPanel.classList.remove('reception-open');receptionPanel.setAttribute('inert','');if(receptionTrigger)receptionTrigger.focus()}
for(const trigger of command.querySelectorAll('[data-reception]')){trigger.addEventListener('click',()=>{receptionTrigger=trigger;selectView(tabButtons.find(tab=>tab.dataset.view===trigger.dataset.reception));receptionPanel.classList.add('reception-open');receptionPanel.removeAttribute('inert');panelClose.focus()})}
panelClose.addEventListener('click',closeReception);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeReception();if(event.key==='Tab'&&receptionPanel.classList.contains('reception-open')){const focusable=[...receptionPanel.querySelectorAll('button:not([tabindex="-1"]),a[href],input,textarea,select')].filter(el=>el.getClientRects().length);const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});command.querySelector('.brand').addEventListener('click',closeReception);
const requestArea=document.createElement('form');
requestArea.className='request-form';
requestArea.innerHTML=`<h3>Хүсэлт илгээх</h3><div class="request-fields"><label>Таны нэр<input name="customer" autocomplete="name" required maxlength="100"></label><label>Утас эсвэл имэйл<input name="contact" required maxlength="150" autocomplete="email"></label></div><label>Ямар ажилд туслах хэрэгтэй вэ?<textarea name="request" required maxlength="2000" rows="3" placeholder="Жишээ: борлуулалтын тайлангаа автоматжуулах"></textarea></label><p class="request-note">Хүсэлтийг FormSubmit үйлчилгээгээр компанийн имэйлд дамжуулна.</p><button type="submit" class="reception-primary">Хүсэлт илгээх</button><p class="request-status" role="status"></p>`;
command.querySelector('#view-contact .contact-prompt').replaceWith(requestArea);



const requestSubject=document.createElement('input');requestSubject.type='hidden';requestSubject.name='_subject';requestSubject.value='Oyun Technology — шинэ хүсэлт';requestArea.append(requestSubject);
const emailLink=document.createElement('a');emailLink.className='company-email';emailLink.href='mailto:oyuntechnology2@gmail.com';emailLink.textContent='oyuntechnology2@gmail.com ↗';command.querySelector('#view-contact .view-heading').after(emailLink);
requestArea.removeAttribute('action');requestArea.removeAttribute('method');requestArea.querySelector('button[type="submit"]').textContent='Имэйлээр илгээх';requestArea.querySelector('.request-note').textContent='Таны имэйл программд хүсэлт нээгдэнэ. Тэндээс Илгээх дарж явуулна.';
requestArea.addEventListener('submit',event=>{event.preventDefault();const values=new FormData(requestArea);const body=`Нэр: ${values.get('customer')}\nХолбоо барих: ${values.get('contact')}\nХэрэгцээ: ${values.get('request')}`;location.href=`mailto:oyuntechnology2@gmail.com?subject=${encodeURIComponent('Oyun Technology — хүсэлт')}&body=${encodeURIComponent(body)}`;requestArea.querySelector('.request-status').textContent='Имэйл программ нээгдээгүй бол дээрх хаяг руу шууд бичээрэй.'});

